### ISSUE TITLE
Data set request

### ISSUE THREAD

**Issue by Wei-Peng-fei** [maynardsd/Hyperspectral-object-tracking-paperlist#1]
Thank you for your work, your work has helped me a lot as a new person. Could you please give me the link of hyperspectral target tracking data set？Now I find the HOT2023 data set, the IMEC25 data set.

**Comment by maynardsd** [comment]
As far as I know, in addition to the two datasets you found, there is also a WHU-Hi-H3 dataset, but this one is not open source.

**Comment by Wei-Peng-fei** [comment]
Thank you！
